apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: k-s
deploy:
  kubectl:
    manifests:
      # Just temporarily
      # - ./infra/k8s-prod/*
      - ./infra/k8s-dev/ingress-srv
      - ./infra/k8s-dev/kitchen-depl
      - ./infra/k8s-dev/kitchen-mongo-depl
      - ./infra/k8s-dev/storage-depl
      - ./infra/k8s-dev/storage-mongo-depl
      - ./infra/k8s-dev/nats-depl
build:
  local:
    push: false
  artifacts:
    - image: rojasleon/kitchen-dev
      context: kitchen
      docker:
        dockerfile: Dockerfile.dev
    - image: rojasleon/storage-dev
      context: storage
      docker:
        dockerfile: Dockerfile.dev
    # - image: rojasleon/client
    #   context: client
    #   docker:
    #     dockerfile: Dockerfile