apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: k-s
deploy:
  kubectl:
    manifests:
      - ./infra/k8s-prod/*
# build:
#   local:
#     push: false
#   artifacts:
#     - image: rojasleon/kitchen
#       context: kitchen
#       docker:
#         dockerfile: Dockerfile
#     - image: rojasleon/storage
#       context: storage
#       docker:
#         dockerfile: Dockerfile
#     - image: rojasleon/client
#       context: client
#       docker:
#         dockerfile: Dockerfile