apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: lunch.dev
      http:
        paths:
          - path: /api/kitchen/
            pathType: Prefix
            backend:
              service:
                name: kitchen-srv
                port:
                  number: 3000
          - path: /api/storage/
            pathType: Prefix
            backend:
              service:
                name: storage-srv
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client-srv
                port:
                  number: 3000