export enum ActionType {
  FETCH_RECIPES_START = 'fetch_recipes_start',
  FETCH_RECIPES_COMPLETE = 'fetch_recipes_complete',
  FETCH_RECIPES_ERROR = 'fetch_recipes_error',
  SELECT_RECIPE_START = 'select_recipe_start',
  SELECT_RECIPE_COMPLETE = 'select_recipe_complete',
  SELECT_RECIPE_ERROR = 'select_recipe_error',
  FETCH_INGREDIENTS_START = 'fetch_ingredients_start',
  FETCH_INGREDIENTS_COMPLETE = 'fetch_ingredients_complete',
  FETCH_INGREDIENTS_ERROR = 'fetch_ingredients_error',
  FETCH_PURCHASES_START = 'fetch_purchases_start',
  FETCH_PURCHASES_COMPLETE = 'fetch_purchases_complete',
  FETCH_PURCHASES_ERROR = 'fetch_purchases_error',
  FETCH_ORDERS_START = 'fetch_orders_start',
  FETCH_ORDERS_COMPLETE = 'fetch_orders_complete',
  FETCH_ORDERS_ERROR = 'fetch_orders_error',
  CREATE_ORDER_START = 'create_order_start',
  CREATE_ORDER_COMPLETE = 'create_complete_start',
  CREATE_ORDER_ERROR = 'create_error_start'
}
