name: tests-storage

on:
  push:
  pull_request:
    paths:
      - 'storage/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: run tests
      run: |
        cd storage && npm install && npm run test:ci
