name: tests-storage

on:
  push:
    paths:
      - 'storage/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: run tests
      run: |
        cd storage && npm ci && npm run build --if-present && npm run test:ci
